### ISSUE TITLE
Another similar project

### ISSUE THREAD

**Issue by anaskaejdar** [muraiki/byzscribe#20]
Good evening, Erik, Christ is Risen!

I don't know another way to contact you, so I'm (ab)using your project's bugtracker system.  Please close this ticket once you see it.  I just wanted to let you know there are other people around who are trying to do the same thing you were trying to do here.  One such person is Charalampos Kornaros, who has a latex package for composing byzantine music.  Another is Trevor Bullock, the guy behind a program called Kassia: a byzantine chant scorer on its own, rather than using latex.  Trevor and I are on Matrix.  My matrix ID is `@tasso:ostavrosnika.com`, send me a DM if you want to be in contact with us.  If you don't have a matrix account, but want one, I own the server, so I can make you an account.  In that case, email me: `zkdarian@gmail.com`

I in particular really like your idea.  It's like a kind of markdown compared to the other formats, it's much much simpler.  Once the current stuff Trevor and I are working on is done, I want to make something similar to this, just with a few changes to the syntax.  But I want people to be able to write something in this simpler syntax and then 'compile' it into the latex or Kassia formats for further formatting, font selection, etc.  And then when that's fully implemented, it's time to make a graphical editor.  Just want you to know I'm really into this.  I like it, well done.

~ Tasso

**Comment by muraiki** [comment]
@maemunman : Truly He is Risen! I'm sorry it's taken me over a year to respond! I obviously haven't been very active on this project or on GitHub in general. I think that my side project bandwidth is full for the time being, but I'm really glad that there are other people working on something like this.

You're correct in that I wanted to create something like markdown: I think that subconsciously, [ABC](https://en.wikipedia.org/wiki/ABC_notation) was an inspiration. At the time I made this, I was a complete noob to programming and also not that well versed in Byzantine chant. I think the lack of domain knowledge was the main blocker, and I haven't necessarily leveled up since then (I can read Byzantine notation decently well, but I'm weak in orthography and terminology). I'd definitely have abbreviations rather than requiring people to write out long English versions of neume names.

I think that having a simple format that compiles into Kassia or latex is a great idea. I actually found Charalampos Kornaros' latex package and thought about doing something similar, but noob programmer + noob latex is a bad combination, haha.

I hope that you are able to make progress on your project. You might be interested in [AGES Initiatives](https://www.agesinitiatives.org/), who created the [Digital Chant Stand](https://www.agesinitiatives.com/dcs/public/dcs/dcs.html). I had a good conversation with Fr. Seraphim a long time ago about creating a non-PDF/Word based format for chant and an open source program for writing it. I don't know how things have changed since then, but he might be able to help you get in touch with people who can help with your project.

Also, you might be interested in the [Trisagion School of Byzantine Music](https://trisagionschool.org/). My friend Amy, a co-founder, applies principles from Montessori learning to teach Byzantine chant. The school could be a good consumer of programs like this, for writing practice pieces and teaching.
